sudo: required
language: node_js

services:
  - docker

branches:
  only:
    - master
    - /^release-[0-9]+\..*$/

addons:
  sonarcloud:
    organization: "open-cluster-management"
    token:
      secure: 
        "cB5QiHDIVLBTHbXzHM27LY4IGfPsngwvE5gQ4UTq0lNeWkhGXb5yosTKAybFH7XznGdGNKS55Ki/iU8vZR0fXPGAP/YkDBbRk5GxK3G4UMhOVYm/AAbasf6HiszaQrHP7VivlgMQqxCIrDAY/udmY77OWGziQYk8UUViHZKqFf+uRqyuzPeuQ7nFVpSbPmYL8xkjIoN5ZiYkDz74xTY8ovKeFeY57KO6hmFa1VvMhaNTwE2OhDazm1TvoMYbx95mBc3L2/NO+yEVuLETwzwClS1wiwyJSr094bSsLEtvaGi0ZnQ05OZ5bzP0FouC9W1sav/HPgO3ZYwLq8SWrw52qsOnbl1CIxCb4a+VWeiBqFGyzsC+ZxiQKZ392ZHgWlBTwLiQtYufpko6n59jptTgirNczorAM2mEtKBk2PcSfdCKukBNcnwKMEcsqb0gSOZjmPqd868iBfI1mRy2SXsIrVl7uvFN6c9peKUH4vWwpGeJfnvFh5ETvxMTDDoIUB8DsLiIHpufUWxf4W9IMXKfnmSy/AcDxlI338Fy7pfiCX0bTWs/4opR8cNsl6nX40R+5fRAjYmtkpcRCjXPSaj6UUrnjtuZkK1ql8RGftrIiNE5IdEZymAuoITfDMiTdMm2YHaRjDIH7jUDODOCqz6siVzjf1CSAoaGhGOVb2A5bnA="

env:
  global:
    # Required
    - OS=linux
    - COMPONENT_TAG_EXTENSION="-${TRAVIS_COMMIT}"
    # Component Specific
    - COMPONENT_INIT_COMMAND=${TRAVIS_BUILD_DIR}/build/install-dependencies.sh
    - COMPONENT_BUILD_COMMAND=${TRAVIS_BUILD_DIR}/build/build.sh
    - COMPONENT_UNIT_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-unit-tests.sh
    - COMPONENT_E2E_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-e2e-tests.sh

stages:
  - build
  - unit-test
  - test-e2e
  - publish
 
before_script:
  - make init

jobs:
  include:
    - stage: build
      name: "Build the image and push"
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - make component/build
        - make component/push
        - make security/scans
    - stage: unit-test
      name: "Build and run unit tests"
      script:
        - chmod +x copyright-check.sh
        - make copyright-check
        - make sonar/js/jest-init
        - make component/test/unit
        - make sonar/js
    - stage: test-e2e
      name: "Run e2e tests"
      if: type = pull_request
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - make component/pull
        - make component/test/e2e
    - stage: publish
      name: "Publish the image to quay with an official version/sha tag and publish entry to integration pipeline stage"
      if: type = push AND branch =~ /^release-[0-9]+\..*$/
      script:
        - make pipeline-manifest/update PIPELINE_MANIFEST_COMPONENT_SHA256=${TRAVIS_COMMIT} PIPELINE_MANIFEST_COMPONENT_REPO=${TRAVIS_REPO_SLUG} PIPELINE_MANIFEST_BRANCH=${TRAVIS_BRANCH}